# -*- coding: utf-8 -*-
"""Dados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VP_HM5r1lqzFpXFVyAMMygmChsckhjbz
"""

import random
import matplotlib.pyplot as plt
import numpy as np 


numero = 102
res = 0;
lanzo = "";
array = [];
resultado = [];
i = 0
aux = 0
aux1 = 0
aux2= 0
aux3 = 0
aux4 = 0
aux5 = 0
aux6 = 0
aux7 = 0
aux8 = 0
aux9 = 0
aux0 = 0

while i < 100:
    i +=1
    dado1 = (random.randint(1,6))
    dado2 = (random.randint(1,6))
    res = dado1 + dado2
    array.append(res)
    
for j in array:
    if j == 2:
        aux = aux + 1
        
    if j == 3:
        aux1 = aux1 + 1
        
    if j == 4:
        aux2 = aux2 + 1
        
    if j == 5:
        aux3 = aux3 + 1
    
    if j == 6:
        aux4 = aux4 + 1
        
    if j == 7:
        aux5 = aux5 + 1
        
    if j == 8:
        aux6 = aux6 + 1
        
    if j == 9:
        aux7 = aux7 + 1
        
    if j == 10:
        aux8 = aux8 + 1
        
    if j == 11:
        aux9 = aux9 + 1
        
    if j == 12:
        aux0 = aux0 + 1

resultado = (aux,aux1, aux2, aux3, aux4, aux5, aux6, aux7, aux8, aux9, aux0)  
cadena =(2,3,4,5,6,7,8,9,10,11,12)
print (resultado)
print (cadena)

n, bins, patches = plt.hist(x=array, bins=12, color='#0504aa',
                            alpha=0.8, rwidth=0.85)
plt.grid(alpha=1)
plt.xlabel('Valores')
plt.ylabel('Frequencia')
plt.title('Lanzamiento de dados')
print("Realizado por: William Chabla")

"""# Sección nueva"""